engines:
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
      - python
      - php
  eslint:
    enabled: true
  fixme:
    enabled: true
  phpmd:
    enabled: true
    checks:
      Naming/ShortVariable:
        enabled: false
        exceptions: id
  phpcodesniffer:
    enabled: true
  phan:
    enabled: true
    config:
      ignore-undeclared: true
      dead-code-detection: true
ratings:
  paths:
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
  - "**.rb"
exclude_paths:
- vendor/
- config
