sudo: required
language: generic
services:
  - docker
before_install:
  - docker pull $DOCKER_REPO || true
  - docker build --cache-from $DOCKER_REPO -t $DOCKER_REPO .
  - docker-compose -f docker-compose-test.yml up -d
  - docker exec -it autowp_imagehost_test_web bash -c "./wait-for-it.sh autowp_imagehost_test_mysql:3306"
  - docker exec -it autowp_imagehost_test_mysql bash -c "mysql -uroot -ppassword -e 'create database image_host;'"
  - docker exec -i autowp_imagehost_test_mysql bash -c "mysql -uroot -ppassword image_host" < test/_files/dump.sql
  
script: 
  - docker exec -it autowp_imagehost_test_web sh -c "./composer.phar cs-check"
#  - docker exec -it autowp_imagehost_test_web sh -c "./composer.phar phpmd"
  - docker exec -it autowp_imagehost_test_web sh -c "php -dzend_extension=xdebug.so vendor/bin/phpunit --coverage-clover ./logs/clover.xml"

after_success:
  - docker exec -it autowp_imagehost_test_web bash -c "./vendor/bin/coveralls -v"
  - docker exec -it autowp_imagehost_test_web bash -c "./vendor/bin/test-reporter -v --coverage-report=./logs/clover.xml"
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push $DOCKER_REPO;
    fi