web:
  image: autowp/image-host
  environment:
    IMAGE_HOST_HOST: localhost
  volumes:
  - ./logs:/var/log:rw
  - ./test/_files/local.php:/app/config/autoload/local.php:ro
  - ./config/application.config.php:/app/config/application.config.php:ro
  - ./view:/app/view:ro
  - ./test:/app/test:ro
#  - ./data:/app/data
  - ./cache:/app/cache:rw
  - ./src:/app/src:ro
  - ./public/image:/app/public/image:rw
  - ./vendor:/app/vendor:ro
  ports:
  - "80:80"
  restart: always
  links:
  - mysql

mysql:
  image: mysql
  restart: always
  environment:
  - "MYSQL_ROOT_PASSWORD=password"
  volumes:
  - "./mysql:/var/lib/mysql"
  - "./mysql.conf.d:/etc/mysql/conf.d"
  expose:
  - "3306"
