web:
  image: autowp/image-host
  container_name: autowp_imagehost_test_web
  environment:
    CODECLIMATE_REPO_TOKEN: ${CODECLIMATE_REPO_TOKEN}
    TRAVIS: ${TRAVIS}
    TRAVIS_JOB_ID: ${TRAVIS_JOB_ID}
    TRAVIS_JOB_NUMBER: ${TRAVIS_JOB_NUMBER}
    TRAVIS_BRANCH: ${TRAVIS_BRANCH}
    TRAVIS_PULL_REQUEST: ${TRAVIS_PULL_REQUEST}
    TRAVIS_PULL_REQUEST_BRANCH: ${TRAVIS_PULL_REQUEST_BRANCH}
    TRAVIS_PULL_REQUEST_SHA: ${TRAVIS_PULL_REQUEST_SHA}
    TRAVIS_BUILD_NUMBER: ${TRAVIS_BUILD_NUMBER}
    TRAVIS_COMMIT: ${TRAVIS_COMMIT}
    TRAVIS_COMMIT_MESSAGE: ${TRAVIS_COMMIT_MESSAGE}
    TRAVIS_COMMIT_RANGE: ${TRAVIS_COMMIT_RANGE}
    TRAVIS_EVENT_TYPE: ${TRAVIS_EVENT_TYPE}
    TRAVIS_TAG: ${TRAVIS_TAG}
    IMAGE_HOST_HOST: localhost
  volumes:
  - ./test/_files/local.php:/app/config/autoload/local.php:ro
  ports:
  - "80:80"
  restart: always
  links:
  - mysql

mysql:
  image: mysql
  container_name: autowp_imagehost_test_mysql
  restart: always
  environment:
  - MYSQL_DATABASE: "image_host"
  - MYSQL_ROOT_PASSWORD: "password"
  expose:
  - "3306"
